# fly.toml app configuration file generated for auth-provider on 2024-02-01T05:34:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "auth-provider"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
